# Generated by Django 2.2.7 on 2019-11-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOMECHEFAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igrediantname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipename', models.CharField(max_length=100)),
                ('ingrediants', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
