# Generated by Django 2.2.7 on 2019-11-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOMECHEFAPP', '0002_auto_20191119_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingrediants',
            new_name='Ingrediant',
        ),
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
    ]
