# Generated by Django 2.2.7 on 2019-11-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOMECHEFAPP', '0003_auto_20191119_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingrediant',
            new_name='Ingredient',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='igrediantname',
            new_name='igredientname',
        ),
    ]
