# Generated by Django 2.2.7 on 2019-11-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOMECHEFAPP', '0004_auto_20191119_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='igredientname',
            new_name='ingredientname',
        ),
    ]
