# Generated by Django 2.2.7 on 2019-11-21 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOMECHEFAPP', '0005_auto_20191119_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingrediants',
            new_name='ingredients',
        ),
    ]
